### ISSUE TITLE
would you provide a guide on how to arrange the dataset file directory structure?

### ISSUE THREAD

**Issue by SeekPoint** [sergii-gavrylov/ShowAndTell#2]
```
MSCOCO
Flickr8k 
Flickr30k 
```

put which file on which location?

**Comment by serhii-havrylov** [comment]
Hi! I hope you can infer that info from these lines [Flickr8k](https://github.com/sergii-gavrylov/ShowAndTell/blob/master/data_preparation/flickr/flickr8k/build_image_text_match.py#L6) [Flickr30k](https://github.com/sergii-gavrylov/ShowAndTell/blob/master/data_preparation/flickr/flickr30k/build_image_text_match.py#L6) [MSCOCO](https://github.com/sergii-gavrylov/ShowAndTell/blob/master/data_preparation/mscoco/build_image_text_match.py#L7) If you still have questions feel free to ask.

**Comment by SeekPoint** [comment]
it looks the system was hang, after several minutes, it reports:

envy@ub1404:/media/envy/data1t/os_prj/github/ShowAndTell$ bash data_preparation/mscoco/build_image_text_match.py
from: can't read /var/mail/collections
data_preparation/mscoco/build_image_text_match.py: line 7: mscoco_captions_files: command not found
data_preparation/mscoco/build_image_text_match.py: line 8: val:: command not found
data_preparation/mscoco/build_image_text_match.py: line 9: mscoco_image_folder: command not found
data_preparation/mscoco/build_image_text_match.py: line 10: val:: command not found
data_preparation/mscoco/build_image_text_match.py: line 11: test2014:: command not found
data_preparation/mscoco/build_image_text_match.py: line 12: mscoco_image_captions_file: command not found
data_preparation/mscoco/build_image_text_match.py: line 15: syntax error near unexpected token `('
data_preparation/mscoco/build_image_text_match.py: line 15:`image_path_to_captions = defaultdict(lambda: defaultdict(list))'
envy@ub1404:/media/envy/data1t/os_prj/github/ShowAndTell$ 

I guess it was caused by the big size of mscoco 

anyone can confirm?

**Comment by serhii-havrylov** [comment]
I am not 100% sure what is going on here, but it seems you run python script as bash script which is clearly not. I used workstation with 32GB RAM, if you have a problem with preprocessing data you can download it directly from my [google drive](https://drive.google.com/folderview?id=0B-bMt9sukkEhfnlhbm9fczhsTWVQcm1yNkpfVExvU19jWmw0bzl1ZTQ1eDVyeW82Vi1pQ1E&usp=sharing)

**Comment by SeekPoint** [comment]
I used the bash, that's a stupid mistake, sorry.
